version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  web-api:
    build:
      context: ./MSAgentFrameworkRAG
      dockerfile: Dockerfile
    container_name: dotnet-web-api
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=RAGAgent;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - Parser__DoclingWorkerUrl=https://YOUR-NGROK-TUNNEL-URL.ngrok-free.dev
      - Storage__RootDirectory=/app/wwwroot/storage
      - OpenAI__ApiKey=YOUR_OPENAI_API_KEY
      - OpenAI__ChatModel=gpt-4.1-mini
      - OpenAI_RAGChatModel= gpt-5-mini
      - OpenAI__EmbeddingModel=text-embedding-3-large
      - Pinecone__ApiKey=YOUR_PINECONE_API_KEY
      - Pinecone__IndexName=contractanalysisrepo
    ports:
      - "5000:8080"
    volumes:
      - shared-storage:/app/wwwroot/storage
    depends_on:
      sql-server:
        condition: service_healthy
    restart: on-failure

volumes:
  sql-data:
  shared-storage:
